In [1]:
import glob
import os
import numpy as np
import time
import math
from DataProcess import *
from SolutionChecker import *
from LocalSearch import *

In [2]:
# l1 = ['dense', 'medium','sparse']
l1 = ['sparse']
common = '_10_30_3_'
filelist = []

for item in l1:
    for i in range(1, 11):
        filelist.append(item + common + str(i)+ '_I')
print(filelist)

['sparse_10_30_3_1_I', 'sparse_10_30_3_2_I', 'sparse_10_30_3_3_I', 'sparse_10_30_3_4_I', 'sparse_10_30_3_5_I', 'sparse_10_30_3_6_I', 'sparse_10_30_3_7_I', 'sparse_10_30_3_8_I', 'sparse_10_30_3_9_I', 'sparse_10_30_3_10_I']


In [4]:
# def visual(x):
#     res = 'Progress: ['
#     if x > 99:
#         for i in range(int(x/2) + 1):
#             res = res + '#'
#     else:
#         for i in range(int(x/2)):
#             res = res + '#'
#         for i in range(50-int(x/2)):
#             res = res + ' '
#     res = res + ']'
#     return res

In [3]:
progress = 0
for item in filelist:
    source_path = os.path.dirname(os.path.abspath('__file__')) +'/InstancesInt/' + item + '.full'
    print(source_path)
#     progress = progress + float(1)/float(len(filelist))*100
#     print(visual(progress), end = '\r')
    EVA_TREE,GRAPH,_ = read_data(source_path)
    endtime,solution,algo_name,exc_time = LocalSearchRandomStart(EVA_TREE,GRAPH,n_iter=10,n_start_points=5)
    create_solution_file(item,solution,endtime,algo_name,exc_time)

/home/th_tran/4IR_Meta_Heuristiqes/Projet_Meta_Heuristiques/InstancesInt/sparse_10_30_3_1_I.full
---------------------------Start n.1---------------------------
Iteration 0:
[77, 138, 156, 167, 134, 177, 190, 128, 107, 130]  =>  156
Iteration 1:
[ 77 128 156 167 134 177 190 138 107 130]  =>  140
Iteration 2:
[ 77 128 156 167 134 177 190 138 107 130]  =>  140
Iteration 3:
[ 77 128 156 167 134 177 190 138 107 130]  =>  140
Iteration 4:
[ 77 128 156 167 134 177 190 138 107 130]  =>  140
Iteration 5:
[ 77 128 156 167 134 177 190 138 107 130]  =>  140
---------------------------Start n.2---------------------------
Iteration 0:
[107, 177, 156, 138, 190, 128, 134, 167, 130, 77]  =>  158
Iteration 1:
[107 177 156 128 190 138 134 167 130  77]  =>  143
Iteration 2:
[107 177 156 128 190 138 134 167 130  77]  =>  143
Iteration 3:
[107 177 156 128 190 138 134 167 130  77]  =>  143
Iteration 4:
[107 177 156 128 190 138 134 167 130  77]  =>  143
Iteration 5:
[107 177 156 128 190 138 134 167 130  77] 

Iteration 5:
[261 221 127  97  88 262 204 160  81 183]  =>  388
---------------------------Start n.2---------------------------
Iteration 0:
[81, 183, 127, 261, 262, 88, 160, 204, 97, 221]  =>  402
Iteration 1:
[261 183 127  81 262  88 160 204  97 221]  =>  388
Iteration 2:
[261 183 127  81 262  88 160 204  97 221]  =>  388
Iteration 3:
[261 183 127  81 262  88 160 204  97 221]  =>  388
Iteration 4:
[261 183 127  81 262  88 160 204  97 221]  =>  388
Iteration 5:
[261 183 127  81 262  88 160 204  97 221]  =>  388
---------------------------Start n.3---------------------------
Iteration 0:
[160, 183, 127, 261, 221, 81, 262, 88, 204, 97]  =>  408
Iteration 1:
[261 183 127 160 221  81 262  88 204  97]  =>  388
Iteration 2:
[261 183 127 160 221  81 262  88 204  97]  =>  388
Iteration 3:
[261 183 127 160 221  81 262  88 204  97]  =>  388
Iteration 4:
[261 183 127 160 221  81 262  88 204  97]  =>  388
Iteration 5:
[261 183 127 160 221  81 262  88 204  97]  =>  388
---------------------------S

Iteration 2:
[142 277  14  96  11  56 267 190  10  97]  =>  229
Iteration 3:
[142 277  14  96  11  56 267 190  10  97]  =>  229
Iteration 4:
[142 277  14  96  11  56 267 190  10  97]  =>  229
Iteration 5:
[142 277  14  96  11  56 267 190  10  97]  =>  229
---------------------------Start n.4---------------------------
Iteration 0:
[142, 96, 56, 14, 267, 11, 190, 97, 277, 10]  =>  241
Iteration 1:
[142, 96, 56, 14, 267, 11, 190, 97, 277, 10]  =>  241
Iteration 2:
[142, 96, 56, 14, 267, 11, 190, 97, 277, 10]  =>  241
Iteration 3:
[142, 96, 56, 14, 267, 11, 190, 97, 277, 10]  =>  241
Iteration 4:
[142, 96, 56, 14, 267, 11, 190, 97, 277, 10]  =>  241
---------------------------Start n.5---------------------------
Iteration 0:
[11, 277, 190, 56, 96, 10, 14, 142, 267, 97]  =>  239
Iteration 1:
[ 11 277  97  56  96  10  14 142 267 190]  =>  233
Iteration 2:
[ 97 277  11  56  96  10  14 142 267 190]  =>  224
Iteration 3:
[ 97 277  11  56  96  10  14 142 267 190]  =>  224
Iteration 4:
[ 97 277 

Iteration 2:
[193 140 166 182 224  48 175  13  97  38]  =>  188
Iteration 3:
[193 140 166 182 224  48 175  13  97  38]  =>  188
Iteration 4:
[193 140 166 182 224  48 175  13  97  38]  =>  188
Iteration 5:
[193 140 166 182 224  48 175  13  97  38]  =>  188


In [ ]:
filename = os.path.dirname(os.path.abspath('__file__')) + '/Borne_Inf_List.csv'
f = open(filename, 'w')
t = 0
f.write('File_name, Nb_evac_nodes, Graph_length, Borne_Inf, Execution_time\n')
for item in filelist:
    print('Generating infimum for ' + item)
    f.write(item + ', ')
    EVA_TREE,GRAPH,NB_NODES = read_data(source_path + item + '.full')
    NB_EVA_NODES = len(EVA_TREE)
    NB_EDGES = len(GRAPH)
    LIST_EVA_NODES = [item[0] for item in EVA_TREE]
    f.write(str(NB_EVA_NODES) + ', ')
    f.write(str(NB_EDGES) + ', ')
    #f.write(str(NB_EVA_NODES * NB_EDGES) + ', ')
    t = time.time()
    res = get_borne_inf(LIST_EVA_NODES,EVA_TREE,GRAPH)
    t = time.time() - t
    f.write(str(res) + ', ')
    f.write(str(t) + '\n')
    
f.close()

In [ ]:
filename = os.path.dirname(os.path.abspath('__file__')) + '/Borne_Sup_List.csv'
f = open(filename, 'w')
min_sol = []
res = 0
avg = 0
min_r = 999999
t = 0
l = []
nb = 50
progress = 0
f.write('File_name, Nb_evac_nodes, Graph_length, Borne_Sup_Min, Borne_Sup_Max, Avg_Execution_time\n')
for item in filelist:
    progress = progress + float(1)/float(len(filelist))*100
    print(visual(progress), end = '\r')
    f.write(item + ', ')
    EVA_TREE,GRAPH,NB_NODES = read_data(source_path + item + '.full')
    NB_EVA_NODES = len(EVA_TREE)
    NB_EDGES = len(GRAPH)
    LIST_EVA_NODES = [item[0] for item in EVA_TREE]
    f.write(str(NB_EVA_NODES) + ', ')
    f.write(str(NB_EDGES) + ', ')
    #f.write(str(NB_EVA_NODES * NB_EDGES) + ', ')
    for i in range(1, nb+1):
        t = time.time()
        res = get_borne_sup(LIST_EVA_NODES,EVA_TREE,GRAPH)[0]
        t = time.time() - t
        l.append(res)
        avg = avg + t/float(nb)
    #print(l)
    f.write(str(min(l)) + ', ')
    f.write(str(max(l)) + ', ')
    f.write(str(avg) + '\n')
    avg = 0
    l = []
    min_r = 999999
    
f.close()

In [ ]:
s = source_path + filelist[0] + '.full'
EVA_TREE,GRAPH,NB_NODES = read_data(s)
print(get_edge_info(57,244,GRAPH))

In [ ]:
s = data_path + 'inputTD'
d = data_path + 'solutionTD'
verify_solution(s,d)

In [7]:
for item in filelist:
    print('Working on ' + item)
    data_path = source_path + item + '.full'
    solution_path = sol_path + item + '.solution'
    verify_solution(data_path,solution_path)
    print('-----------------------------')

Working on dense_10_30_3_1_I
CREATION TASKS & VERIFY CONSTRAINTS
227 80
344 134
323 100
268 80
275 54
279 86
359 48
384 19
163 0
285 0
-----------------------------
CHECK F_OBJECTIF
-----------------------------
End time is :  180
True
-----------------------------
END
-----------------------------
-----------------------------
Working on dense_10_30_3_2_I
CREATION TASKS & VERIFY CONSTRAINTS
197 83
356 51
501 178
21 145
18 54
284 0
277 147
431 0
516 114
514 192
-----------------------------
CHECK F_OBJECTIF
-----------------------------
End time is :  253
True
-----------------------------
END
-----------------------------
-----------------------------
Working on dense_10_30_3_3_I
CREATION TASKS & VERIFY CONSTRAINTS
29 75
138 170
505 170
382 155
17 135
237 173
201 170
447 54
281 0
472 162
-----------------------------
CHECK F_OBJECTIF
-----------------------------
End time is :  254
True
-----------------------------
END
-----------------------------
-----------------------------
Worki