In [1]:
import glob
import os
import numpy as np
import time
import math
from DataProcess import *
from SolutionChecker import *
from LocalSearch import *

In [5]:
# l1 = ['dense', 'medium','sparse']
l1 = ['dense', 'medium']
common = '_10_30_3_'
filelist = []

for item in l1:
    for i in range(1, 11):
        filelist.append(item + common + str(i)+ '_I')
print(filelist)

['dense_10_30_3_1_I', 'dense_10_30_3_2_I', 'dense_10_30_3_3_I', 'dense_10_30_3_4_I', 'dense_10_30_3_5_I', 'dense_10_30_3_6_I', 'dense_10_30_3_7_I', 'dense_10_30_3_8_I', 'dense_10_30_3_9_I', 'dense_10_30_3_10_I', 'medium_10_30_3_1_I', 'medium_10_30_3_2_I', 'medium_10_30_3_3_I', 'medium_10_30_3_4_I', 'medium_10_30_3_5_I', 'medium_10_30_3_6_I', 'medium_10_30_3_7_I', 'medium_10_30_3_8_I', 'medium_10_30_3_9_I', 'medium_10_30_3_10_I']


In [4]:
# def visual(x):
#     res = 'Progress: ['
#     if x > 99:
#         for i in range(int(x/2) + 1):
#             res = res + '#'
#     else:
#         for i in range(int(x/2)):
#             res = res + '#'
#         for i in range(50-int(x/2)):
#             res = res + ' '
#     res = res + ']'
#     return res

In [6]:
progress = 0
for item in filelist:
    source_path = os.path.dirname(os.path.abspath('__file__')) +'/InstancesInt/' + item + '.full'
    print(source_path)
#     progress = progress + float(1)/float(len(filelist))*100
#     print(visual(progress), end = '\r')
    EVA_TREE,GRAPH,_ = read_data(source_path)
    endtime,solution,algo_name,exc_time = LocalSearchRandomStart(EVA_TREE,GRAPH,n_iter=10,n_start_points=5)
    create_solution_file(item,solution,endtime,algo_name,exc_time)

/home/th_tran/4IR_Meta_Heuristiqes/Projet_Meta_Heuristiques/InstancesInt/dense_10_30_3_1_I.full
---------------------------Start n.1---------------------------
Iteration 0:
[285, 279, 275, 344, 323, 163, 384, 268, 227, 359]  =>  184
Iteration 1:
[285 384 275 344 323 163 279 268 227 359]  =>  180
Iteration 2:
[285 384 275 344 323 163 279 268 227 359]  =>  180
Iteration 3:
[285 384 275 344 323 163 279 268 227 359]  =>  180
Iteration 4:
[285 384 275 344 323 163 279 268 227 359]  =>  180
Iteration 5:
[285 384 275 344 323 163 279 268 227 359]  =>  180
---------------------------Start n.2---------------------------
Iteration 0:
[279, 344, 275, 323, 268, 227, 163, 359, 285, 384]  =>  207
Iteration 1:
[285 344 275 323 268 227 163 359 279 384]  =>  180
Iteration 2:
[285 344 275 323 268 227 163 359 279 384]  =>  180
Iteration 3:
[285 344 275 323 268 227 163 359 279 384]  =>  180
Iteration 4:
[285 344 275 323 268 227 163 359 279 384]  =>  180
Iteration 5:
[285 344 275 323 268 227 163 359 279 384]

Iteration 2:
[349 304 461 465 344 162 151 133 213 268]  =>  388
Iteration 3:
[349 304 461 465 344 162 151 133 213 268]  =>  388
Iteration 4:
[349 304 461 465 344 162 151 133 213 268]  =>  388
Iteration 5:
[349 304 461 465 344 162 151 133 213 268]  =>  388
---------------------------Start n.4---------------------------
Iteration 0:
[133, 304, 213, 344, 465, 162, 268, 151, 461, 349]  =>  399
Iteration 1:
[349 304 213 344 465 162 268 151 461 133]  =>  388
Iteration 2:
[349 304 213 344 465 162 268 151 461 133]  =>  388
Iteration 3:
[349 304 213 344 465 162 268 151 461 133]  =>  388
Iteration 4:
[349 304 213 344 465 162 268 151 461 133]  =>  388
Iteration 5:
[349 304 213 344 465 162 268 151 461 133]  =>  388
---------------------------Start n.5---------------------------
Iteration 0:
[344, 213, 461, 304, 162, 268, 349, 465, 133, 151]  =>  393
Iteration 1:
[349 213 461 304 162 268 344 465 133 151]  =>  388
Iteration 2:
[349 213 461 304 162 268 344 465 133 151]  =>  388
Iteration 3:
[349 213 

Iteration 5:
[430 257 221  95 337 109 389 289  86 315]  =>  420
/home/th_tran/4IR_Meta_Heuristiqes/Projet_Meta_Heuristiques/InstancesInt/dense_10_30_3_8_I.full
---------------------------Start n.1---------------------------
Iteration 0:
[174, 346, 427, 236, 233, 493, 273, 489, 70, 370]  =>  354
Iteration 1:
[ 70 346 427 236 233 493 273 489 174 370]  =>  341
Iteration 2:
[ 70 346 427 236 233 493 273 489 174 370]  =>  341
Iteration 3:
[ 70 346 427 236 233 493 273 489 174 370]  =>  341
Iteration 4:
[ 70 346 427 236 233 493 273 489 174 370]  =>  341
Iteration 5:
[ 70 346 427 236 233 493 273 489 174 370]  =>  341
---------------------------Start n.2---------------------------
Iteration 0:
[174, 233, 70, 370, 236, 427, 493, 346, 489, 273]  =>  354
Iteration 1:
[ 70 233 174 370 236 427 493 346 489 273]  =>  341
Iteration 2:
[ 70 233 174 370 236 427 493 346 489 273]  =>  341
Iteration 3:
[ 70 233 174 370 236 427 493 346 489 273]  =>  341
Iteration 4:
[ 70 233 174 370 236 427 493 346 489 273]  

Iteration 1:
[221 285 271 256 182 132 302 218 226 213]  =>  287
Iteration 2:
[221 285 271 256 182 132 302 218 226 213]  =>  287
Iteration 3:
[221 285 271 256 182 132 302 218 226 213]  =>  287
Iteration 4:
[221 285 271 256 182 132 302 218 226 213]  =>  287
Iteration 5:
[221 285 271 256 182 132 302 218 226 213]  =>  287
---------------------------Start n.4---------------------------
Iteration 0:
[213, 221, 285, 256, 218, 271, 182, 226, 302, 132]  =>  288
Iteration 1:
[302 221 285 256 218 271 182 226 213 132]  =>  287
Iteration 2:
[302 221 285 256 218 271 182 226 213 132]  =>  287
Iteration 3:
[302 221 285 256 218 271 182 226 213 132]  =>  287
Iteration 4:
[302 221 285 256 218 271 182 226 213 132]  =>  287
Iteration 5:
[302 221 285 256 218 271 182 226 213 132]  =>  287
---------------------------Start n.5---------------------------
Iteration 0:
[271, 213, 285, 256, 302, 221, 218, 182, 226, 132]  =>  315
Iteration 1:
[302 213 285 256 271 221 218 182 226 132]  =>  287
Iteration 2:
[302 213 

Iteration 5:
[289 176 230 256 119 379 134 294 125 377]  =>  393
/home/th_tran/4IR_Meta_Heuristiqes/Projet_Meta_Heuristiques/InstancesInt/medium_10_30_3_5_I.full
---------------------------Start n.1---------------------------
Iteration 0:
[420, 226, 393, 259, 39, 105, 365, 108, 192, 184]  =>  405
Iteration 1:
[420, 226, 393, 259, 39, 105, 365, 108, 192, 184]  =>  405
Iteration 2:
[420, 226, 393, 259, 39, 105, 365, 108, 192, 184]  =>  405
Iteration 3:
[420, 226, 393, 259, 39, 105, 365, 108, 192, 184]  =>  405
Iteration 4:
[420, 226, 393, 259, 39, 105, 365, 108, 192, 184]  =>  405
---------------------------Start n.2---------------------------
Iteration 0:
[226, 192, 39, 393, 105, 365, 184, 108, 420, 259]  =>  411
Iteration 1:
[105 192  39 393 226 365 184 108 420 259]  =>  405
Iteration 2:
[105 192  39 393 226 365 184 108 420 259]  =>  405
Iteration 3:
[105 192  39 393 226 365 184 108 420 259]  =>  405
Iteration 4:
[105 192  39 393 226 365 184 108 420 259]  =>  405
Iteration 5:
[105 192  

Iteration 1:
[321 403 178 251 339  65 367  89 421 151]  =>  290
Iteration 2:
[321 403 178 251 339  65 367  89 421 151]  =>  290
Iteration 3:
[321 403 178 251 339  65 367  89 421 151]  =>  290
Iteration 4:
[321 403 178 251 339  65 367  89 421 151]  =>  290
Iteration 5:
[321 403 178 251 339  65 367  89 421 151]  =>  290
---------------------------Start n.4---------------------------
Iteration 0:
[251, 367, 151, 321, 89, 65, 421, 178, 339, 403]  =>  293
Iteration 1:
[ 65 367 151 321  89 251 421 178 339 403]  =>  290
Iteration 2:
[ 65 367 151 321  89 251 421 178 339 403]  =>  290
Iteration 3:
[ 65 367 151 321  89 251 421 178 339 403]  =>  290
Iteration 4:
[ 65 367 151 321  89 251 421 178 339 403]  =>  290
Iteration 5:
[ 65 367 151 321  89 251 421 178 339 403]  =>  290
---------------------------Start n.5---------------------------
Iteration 0:
[367, 178, 65, 339, 89, 403, 151, 321, 251, 421]  =>  300
Iteration 1:
[321 178  65 339  89 403 151 367 251 421]  =>  290
Iteration 2:
[321 178  65 

In [3]:
item = 'sparse_10_30_3_4_I'
source_path = os.path.dirname(os.path.abspath('__file__')) +'/InstancesInt/' +item + '.full'
print(source_path)
#     progress = progress + float(1)/float(len(filelist))*100
#     print(visual(progress), end = '\r')
EVA_TREE,GRAPH,_ = read_data(source_path)
endtime,solution,algo_name,exc_time = LocalSearchRandomStart(EVA_TREE,GRAPH,n_iter=10,n_start_points=5)
create_solution_file(item,solution,endtime,algo_name,exc_time)
print(check_a_solution(source_path,solution))


/home/th_tran/4IR_Meta_Heuristiqes/Projet_Meta_Heuristiques/InstancesInt/sparse_10_30_3_4_I.full
---------------------------Start n.1---------------------------
Iteration 0:
[160, 127, 183, 97, 88, 221, 261, 262, 204, 81]  =>  408
Iteration 1:
[261 127 183  97  88 221 160 262 204  81]  =>  388
Iteration 2:
[261 127 183  97  88 221 160 262 204  81]  =>  388
Iteration 3:
[261 127 183  97  88 221 160 262 204  81]  =>  388
Iteration 4:
[261 127 183  97  88 221 160 262 204  81]  =>  388
Iteration 5:
[261 127 183  97  88 221 160 262 204  81]  =>  388
---------------------------Start n.2---------------------------
Iteration 0:
[221, 183, 127, 160, 262, 204, 261, 88, 97, 81]  =>  408
Iteration 1:
[261 183 127 160 262 204 221  88  97  81]  =>  388
Iteration 2:
[261 183 127 160 262 204 221  88  97  81]  =>  388
Iteration 3:
[261 183 127 160 262 204 221  88  97  81]  =>  388
Iteration 4:
[261 183 127 160 262 204 221  88  97  81]  =>  388
Iteration 5:
[261 183 127 160 262 204 221  88  97  81]  => 

In [ ]:
filename = os.path.dirname(os.path.abspath('__file__')) + '/Borne_Inf_List.csv'
f = open(filename, 'w')
t = 0
f.write('File_name, Nb_evac_nodes, Graph_length, Borne_Inf, Execution_time\n')
for item in filelist:
    print('Generating infimum for ' + item)
    f.write(item + ', ')
    EVA_TREE,GRAPH,NB_NODES = read_data(source_path + item + '.full')
    NB_EVA_NODES = len(EVA_TREE)
    NB_EDGES = len(GRAPH)
    LIST_EVA_NODES = [item[0] for item in EVA_TREE]
    f.write(str(NB_EVA_NODES) + ', ')
    f.write(str(NB_EDGES) + ', ')
    #f.write(str(NB_EVA_NODES * NB_EDGES) + ', ')
    t = time.time()
    res = get_borne_inf(LIST_EVA_NODES,EVA_TREE,GRAPH)
    t = time.time() - t
    f.write(str(res) + ', ')
    f.write(str(t) + '\n')
    
f.close()

In [ ]:
filename = os.path.dirname(os.path.abspath('__file__')) + '/Borne_Sup_List.csv'
f = open(filename, 'w')
min_sol = []
res = 0
avg = 0
min_r = 999999
t = 0
l = []
nb = 50
progress = 0
f.write('File_name, Nb_evac_nodes, Graph_length, Borne_Sup_Min, Borne_Sup_Max, Avg_Execution_time\n')
for item in filelist:
    progress = progress + float(1)/float(len(filelist))*100
    print(visual(progress), end = '\r')
    f.write(item + ', ')
    EVA_TREE,GRAPH,NB_NODES = read_data(source_path + item + '.full')
    NB_EVA_NODES = len(EVA_TREE)
    NB_EDGES = len(GRAPH)
    LIST_EVA_NODES = [item[0] for item in EVA_TREE]
    f.write(str(NB_EVA_NODES) + ', ')
    f.write(str(NB_EDGES) + ', ')
    #f.write(str(NB_EVA_NODES * NB_EDGES) + ', ')
    for i in range(1, nb+1):
        t = time.time()
        res = get_borne_sup(LIST_EVA_NODES,EVA_TREE,GRAPH)[0]
        t = time.time() - t
        l.append(res)
        avg = avg + t/float(nb)
    #print(l)
    f.write(str(min(l)) + ', ')
    f.write(str(max(l)) + ', ')
    f.write(str(avg) + '\n')
    avg = 0
    l = []
    min_r = 999999
    
f.close()

In [ ]:
s = source_path + filelist[0] + '.full'
EVA_TREE,GRAPH,NB_NODES = read_data(s)
print(get_edge_info(57,244,GRAPH))

In [ ]:
s = data_path + 'inputTD'
d = data_path + 'solutionTD'
verify_solution(s,d)

In [7]:
for item in filelist:
    print('Working on ' + item)
    data_path = source_path + item + '.full'
    solution_path = sol_path + item + '.solution'
    verify_solution(data_path,solution_path)
    print('-----------------------------')

Working on dense_10_30_3_1_I
CREATION TASKS & VERIFY CONSTRAINTS
227 80
344 134
323 100
268 80
275 54
279 86
359 48
384 19
163 0
285 0
-----------------------------
CHECK F_OBJECTIF
-----------------------------
End time is :  180
True
-----------------------------
END
-----------------------------
-----------------------------
Working on dense_10_30_3_2_I
CREATION TASKS & VERIFY CONSTRAINTS
197 83
356 51
501 178
21 145
18 54
284 0
277 147
431 0
516 114
514 192
-----------------------------
CHECK F_OBJECTIF
-----------------------------
End time is :  253
True
-----------------------------
END
-----------------------------
-----------------------------
Working on dense_10_30_3_3_I
CREATION TASKS & VERIFY CONSTRAINTS
29 75
138 170
505 170
382 155
17 135
237 173
201 170
447 54
281 0
472 162
-----------------------------
CHECK F_OBJECTIF
-----------------------------
End time is :  254
True
-----------------------------
END
-----------------------------
-----------------------------
Worki