In [1]:
import glob
import os
import numpy as np
import time
import math
from DataProcess import *
from SolutionChecker import *
from LocalSearch import *
import cProfile

In [2]:
l1 = ['dense', 'medium', 'sparse']
common = '_10_30_3_'
filelist = []
for item in l1:
    for i in range(1, 11):
        filelist.append(item + common + str(i)+ '_I')
print(filelist)

['dense_10_30_3_1_I', 'dense_10_30_3_2_I', 'dense_10_30_3_3_I', 'dense_10_30_3_4_I', 'dense_10_30_3_5_I', 'dense_10_30_3_6_I', 'dense_10_30_3_7_I', 'dense_10_30_3_8_I', 'dense_10_30_3_9_I', 'dense_10_30_3_10_I', 'medium_10_30_3_1_I', 'medium_10_30_3_2_I', 'medium_10_30_3_3_I', 'medium_10_30_3_4_I', 'medium_10_30_3_5_I', 'medium_10_30_3_6_I', 'medium_10_30_3_7_I', 'medium_10_30_3_8_I', 'medium_10_30_3_9_I', 'medium_10_30_3_10_I', 'sparse_10_30_3_1_I', 'sparse_10_30_3_2_I', 'sparse_10_30_3_3_I', 'sparse_10_30_3_4_I', 'sparse_10_30_3_5_I', 'sparse_10_30_3_6_I', 'sparse_10_30_3_7_I', 'sparse_10_30_3_8_I', 'sparse_10_30_3_9_I', 'sparse_10_30_3_10_I']


In [3]:
source_path = os.path.dirname(os.path.abspath('__file__')) + '/InstancesInt/'
sol_path = os.path.dirname(os.path.abspath('__file__')) + '/Solutions_LocalSearchRandom_2_Start_Pts/'
data_path = os.path.dirname(os.path.abspath('__file__')) + '/data/'

In [6]:
progress = 0
for item in filelist:
    progress = progress + float(1)/float(len(filelist))*100
    print(visual(progress), end = '\r')
    EVA_TREE,GRAPH,_ = read_data(source_path + item + '.full')
    endtime,solution,algo_name,exc_time = LocalSearchRandomStart2(EVA_TREE,GRAPH,n_iter=10,n_start_points=5)
    create_solution_file3(item,solution,endtime,algo_name,exc_time)

---------------------------Start n.1---------------------------
Iteration 0:
[384, 275, 279, 268, 344, 163, 227, 359, 323, 285]  =>  184
Iteration 1:
[227 275 279 268 344 163 384 359 323 285]  =>  181
Iteration 2:
[227 275 279 268 344 163 384 359 323 285]  =>  181
Iteration 3:
[227 275 279 268 344 163 384 359 323 285]  =>  181
Iteration 4:
[227 275 279 268 344 163 384 359 323 285]  =>  181
Iteration 5:
[227 275 279 268 344 163 384 359 323 285]  =>  181
----------------------------------------------------------------
---------------------------Start n.2---------------------------
Iteration 0:
[323, 279, 344, 275, 163, 384, 268, 285, 227, 359]  =>  207
Iteration 1:
[323 285 344 275 163 384 268 279 227 359]  =>  180
Iteration 2:
[323 285 344 275 163 384 268 279 227 359]  =>  180
Iteration 3:
[323 285 344 275 163 384 268 279 227 359]  =>  180
Iteration 4:
[323 285 344 275 163 384 268 279 227 359]  =>  180
Iteration 5:
[323 285 344 275 163 384 268 279 227 359]  =>  180
---------------------

----------------------------------------------------------------
---------------------------Start n.2---------------------------
Iteration 0:
[344, 162, 133, 461, 268, 349, 465, 151, 213, 304]  =>  393
Iteration 1:
[349 162 133 461 268 344 465 151 213 304]  =>  388
Iteration 2:
[349 162 133 461 268 344 465 151 213 304]  =>  388
Iteration 3:
[349 162 133 461 268 344 465 151 213 304]  =>  388
Iteration 4:
[349 162 133 461 268 344 465 151 213 304]  =>  388
Iteration 5:
[349 162 133 461 268 344 465 151 213 304]  =>  388
----------------------------------------------------------------
---------------------------Start n.3---------------------------
Iteration 0:
[465, 344, 133, 461, 268, 213, 304, 162, 151, 349]  =>  409
Iteration 1:
[349 344 133 461 268 213 304 162 151 465]  =>  388
Iteration 2:
[349 344 133 461 268 213 304 162 151 465]  =>  388
Iteration 3:
[349 344 133 461 268 213 304 162 151 465]  =>  388
Iteration 4:
[349 344 133 461 268 213 304 162 151 465]  =>  388
Iteration 5:
[349 34

Iteration 4:
[430, 389, 315, 289, 95, 337, 109, 86, 257, 221]  =>  420
----------------------------------------------------------------
---------------------------Start n.3---------------------------
Iteration 0:
[289, 337, 430, 221, 109, 95, 315, 86, 257, 389]  =>  428
Iteration 1:
[430 337 289 221 109  95 315  86 257 389]  =>  420
Iteration 2:
[430 337 289 221 109  95 315  86 257 389]  =>  420
Iteration 3:
[430 337 289 221 109  95 315  86 257 389]  =>  420
Iteration 4:
[430 337 289 221 109  95 315  86 257 389]  =>  420
Iteration 5:
[430 337 289 221 109  95 315  86 257 389]  =>  420
----------------------------------------------------------------
---------------------------Start n.4---------------------------
Iteration 0:
[389, 337, 86, 221, 109, 430, 315, 289, 95, 257]  =>  422
Iteration 1:
[430 337  86 221 109 389 315 289  95 257]  =>  420
Iteration 2:
[430 337  86 221 109 389 315 289  95 257]  =>  420
Iteration 3:
[430 337  86 221 109 389 315 289  95 257]  =>  420
Iteration 4:
[430

Iteration 4:
[386 101 523 411 333 348  89 286 206  18]  =>  389
Iteration 5:
[386 101 523 411 333 348  89 286 206  18]  =>  389
----------------------------------------------------------------
---------------------------Start n.4---------------------------
Iteration 0:
[348, 101, 18, 386, 523, 333, 206, 89, 411, 286]  =>  390
Iteration 1:
[386 101  18 348 523 333 206  89 411 286]  =>  389
Iteration 2:
[386 101  18 348 523 333 206  89 411 286]  =>  389
Iteration 3:
[386 101  18 348 523 333 206  89 411 286]  =>  389
Iteration 4:
[386 101  18 348 523 333 206  89 411 286]  =>  389
Iteration 5:
[386 101  18 348 523 333 206  89 411 286]  =>  389
----------------------------------------------------------------
---------------------------Start n.5---------------------------
Iteration 0:
[18, 206, 286, 333, 89, 101, 386, 348, 411, 523]  =>  390
Iteration 1:
[386 206 286 333  89 101  18 348 411 523]  =>  389
Iteration 2:
[386 206 286 333  89 101  18 348 411 523]  =>  389
Iteration 3:
[386 206 28

Iteration 2:
[331 376  23 217 178 136 408 258 107 421]  =>  350
Iteration 3:
[331 376  23 217 178 136 408 258 107 421]  =>  350
Iteration 4:
[331 376  23 217 178 136 408 258 107 421]  =>  350
Iteration 5:
[331 376  23 217 178 136 408 258 107 421]  =>  350
Iteration 6:
[331 376  23 217 178 136 408 258 107 421]  =>  350
----------------------------------------------------------------
---------------------------Start n.5---------------------------
Iteration 0:
[376, 178, 331, 107, 217, 408, 23, 258, 421, 136]  =>  356
Iteration 1:
[ 23 178 331 107 217 408 376 258 421 136]  =>  351
Iteration 2:
[ 23 178 331 107 217 408 376 258 421 136]  =>  351
Iteration 3:
[ 23 178 331 107 217 408 376 258 421 136]  =>  351
Iteration 4:
[ 23 178 331 107 217 408 376 258 421 136]  =>  351
Iteration 5:
[ 23 178 331 107 217 408 376 258 421 136]  =>  351
----------------------------------------------------------------
---------------------------Start n.1---------------------------
Iteration 0:
[176, 379, 294, 2

Iteration 1:
[149 175 184 331 174 143 399 285 319 111]  =>  283
Iteration 2:
[149 175 184 331 174 143 399 285 319 111]  =>  283
Iteration 3:
[149 175 184 331 174 143 399 285 319 111]  =>  283
Iteration 4:
[149 175 184 331 174 143 399 285 319 111]  =>  283
Iteration 5:
[149 175 184 331 174 143 399 285 319 111]  =>  283
----------------------------------------------------------------
---------------------------Start n.1---------------------------
Iteration 0:
[242, 286, 363, 328, 224, 90, 205, 77, 95, 275]  =>  430
Iteration 1:
[ 77 286 363 328 224  90 205 242  95 275]  =>  426
Iteration 2:
[ 77 286 363 328 224  90 205 242  95 275]  =>  426
Iteration 3:
[ 77 286 363 328 224  90 205 242  95 275]  =>  426
Iteration 4:
[ 77 286 363 328 224  90 205 242  95 275]  =>  426
Iteration 5:
[ 77 286 363 328 224  90 205 242  95 275]  =>  426
----------------------------------------------------------------
---------------------------Start n.2---------------------------
Iteration 0:
[95, 328, 275, 205,

Iteration 2:
[337  84 299 281 317  96 297  32 240 183]  =>  398
Iteration 3:
[337  84 299 281 317  96 297  32 240 183]  =>  398
Iteration 4:
[337  84 299 281 317  96 297  32 240 183]  =>  398
Iteration 5:
[337  84 299 281 317  96 297  32 240 183]  =>  398
----------------------------------------------------------------
---------------------------Start n.2---------------------------
Iteration 0:
[84, 183, 337, 32, 96, 299, 317, 240, 281, 297]  =>  411
Iteration 1:
[337 183  84  32  96 299 317 240 281 297]  =>  398
Iteration 2:
[337 183  84  32  96 299 317 240 281 297]  =>  398
Iteration 3:
[337 183  84  32  96 299 317 240 281 297]  =>  398
Iteration 4:
[337 183  84  32  96 299 317 240 281 297]  =>  398
Iteration 5:
[337 183  84  32  96 299 317 240 281 297]  =>  398
----------------------------------------------------------------
---------------------------Start n.3---------------------------
Iteration 0:
[337, 183, 96, 84, 317, 281, 297, 32, 299, 240]  =>  398
Iteration 1:
[337, 183, 96

Iteration 2:
[ 60 196 127 219 178  99 138 253 247  79]  =>  278
Iteration 3:
[ 60  79 127 219 178  99 138 253 247 196]  =>  272
Iteration 4:
[ 60  79 127 219 178  99 138 253 247 196]  =>  272
Iteration 5:
[ 60  79 127 219 178  99 138 253 247 196]  =>  272
Iteration 6:
[ 60  79 127 219 178  99 138 253 247 196]  =>  272
Iteration 7:
[ 60  79 127 219 178  99 138 253 247 196]  =>  272
----------------------------------------------------------------
---------------------------Start n.2---------------------------
Iteration 0:
[247, 196, 253, 60, 99, 79, 138, 127, 178, 219]  =>  326
Iteration 1:
[247 196  99  60 253  79 138 127 178 219]  =>  286
Iteration 2:
[247 196  99  60 253  79 138 127 178 219]  =>  286
Iteration 3:
[247 196  99  60 253  79 138 127 178 219]  =>  286
Iteration 4:
[247 196  99  60 253  79 138 127 178 219]  =>  286
Iteration 5:
[247 196  99  60 253  79 138 127 178 219]  =>  286
----------------------------------------------------------------
---------------------------Start

Iteration 1:
[256, 121, 193, 168, 111, 56, 108, 0, 88, 204]  =>  211
Iteration 2:
[256, 121, 193, 168, 111, 56, 108, 0, 88, 204]  =>  211
Iteration 3:
[256, 121, 193, 168, 111, 56, 108, 0, 88, 204]  =>  211
Iteration 4:
[256, 121, 193, 168, 111, 56, 108, 0, 88, 204]  =>  211
----------------------------------------------------------------
---------------------------Start n.2---------------------------
Iteration 0:
[168, 193, 111, 121, 204, 0, 56, 256, 88, 108]  =>  217
Iteration 1:
[168 256 111 121 204   0  56 193  88 108]  =>  211
Iteration 2:
[168 256 111 121 204   0  56 193  88 108]  =>  211
Iteration 3:
[168 256 111 121 204   0  56 193  88 108]  =>  211
Iteration 4:
[168 256 111 121 204   0  56 193  88 108]  =>  211
Iteration 5:
[168 256 111 121 204   0  56 193  88 108]  =>  211
----------------------------------------------------------------
---------------------------Start n.3---------------------------
Iteration 0:
[108, 168, 121, 193, 204, 0, 111, 88, 56, 256]  =>  211
Iteratio

Iteration 2:
[ 22  19   3   0  60 209 176 219 191 256]  =>  289
Iteration 3:
[ 22  19   3   0  60 209 176 219 191 256]  =>  289
Iteration 4:
[ 22  19   3   0  60 209 176 219 191 256]  =>  289
Iteration 5:
[ 22  19   3   0  60 209 176 219 191 256]  =>  289
Iteration 6:
[ 22  19   3   0  60 209 176 219 191 256]  =>  289
----------------------------------------------------------------
---------------------------Start n.2---------------------------
Iteration 0:
[219, 256, 176, 0, 60, 22, 19, 209, 191, 3]  =>  332
Iteration 1:
[219 256   3   0  60  22  19 209 191 176]  =>  299
Iteration 2:
[ 22 256   3   0  60 219  19 209 191 176]  =>  289
Iteration 3:
[ 22 256   3   0  60 219  19 209 191 176]  =>  289
Iteration 4:
[ 22 256   3   0  60 219  19 209 191 176]  =>  289
Iteration 5:
[ 22 256   3   0  60 219  19 209 191 176]  =>  289
Iteration 6:
[ 22 256   3   0  60 219  19 209 191 176]  =>  289
----------------------------------------------------------------
---------------------------Start n.3

In [5]:
def visual(x):
    res = 'Progress: ['
    if x > 99:
        for i in range(int(x/2) + 1):
            res = res + '#'
    else:
        for i in range(int(x/2)):
            res = res + '#'
        for i in range(50-int(x/2)):
            res = res + ' '
    res = res + ']'
    return res

In [ ]:
filename = os.path.dirname(os.path.abspath('__file__')) + '/Borne_Inf_List.csv'
f = open(filename, 'w')
t = 0
f.write('File_name, Nb_evac_nodes, Graph_length, Borne_Inf, Execution_time\n')
for item in filelist:
    print('Generating infimum for ' + item)
    f.write(item + ', ')
    EVA_TREE,GRAPH,NB_NODES = read_data(source_path + item + '.full')
    NB_EVA_NODES = len(EVA_TREE)
    NB_EDGES = len(GRAPH)
    LIST_EVA_NODES = [item[0] for item in EVA_TREE]
    f.write(str(NB_EVA_NODES) + ', ')
    f.write(str(NB_EDGES) + ', ')
    #f.write(str(NB_EVA_NODES * NB_EDGES) + ', ')
    t = time.time()
    res = get_borne_inf(LIST_EVA_NODES,EVA_TREE,GRAPH)
    t = time.time() - t
    f.write(str(res) + ', ')
    f.write(str(t) + '\n')
    
f.close()

In [ ]:
filename = os.path.dirname(os.path.abspath('__file__')) + '/Borne_Sup_List.csv'
f = open(filename, 'w')
min_sol = []
res = 0
avg = 0
min_r = 999999
t = 0
l = []
nb = 50
progress = 0
f.write('File_name, Nb_evac_nodes, Graph_length, Borne_Sup_Min, Borne_Sup_Max, Avg_Execution_time\n')
for item in filelist:
    progress = progress + float(1)/float(len(filelist))*100
    print(visual(progress), end = '\r')
    f.write(item + ', ')
    EVA_TREE,GRAPH,NB_NODES = read_data(source_path + item + '.full')
    NB_EVA_NODES = len(EVA_TREE)
    NB_EDGES = len(GRAPH)
    LIST_EVA_NODES = [item[0] for item in EVA_TREE]
    f.write(str(NB_EVA_NODES) + ', ')
    f.write(str(NB_EDGES) + ', ')
    #f.write(str(NB_EVA_NODES * NB_EDGES) + ', ')
    for i in range(1, nb+1):
        t = time.time()
        res = get_borne_sup(LIST_EVA_NODES,EVA_TREE,GRAPH)[0]
        t = time.time() - t
        l.append(res)
        avg = avg + t/float(nb)
    #print(l)
    f.write(str(min(l)) + ', ')
    f.write(str(max(l)) + ', ')
    f.write(str(avg) + '\n')
    avg = 0
    l = []
    min_r = 999999
    
f.close()

In [ ]:
s = source_path + filelist[0] + '.full'
EVA_TREE,GRAPH,NB_NODES = read_data(s)
print(get_edge_info(57,244,GRAPH))

In [ ]:
s = data_path + 'inputTD'
d = data_path + 'solutionTD'
verify_solution(s,d)

In [7]:
for item in filelist:
    print('Working on ' + item)
    data_path = source_path + item + '.full'
    solution_path = sol_path + item + '.solution'
    verify_solution(data_path,solution_path)
    print('-----------------------------')

Working on dense_10_30_3_1_I
CREATION TASKS & VERIFY CONSTRAINTS
227 80
344 134
323 100
268 80
275 54
279 86
359 48
384 19
163 0
285 0
-----------------------------
CHECK F_OBJECTIF
-----------------------------
End time is :  180
True
-----------------------------
END
-----------------------------
-----------------------------
Working on dense_10_30_3_2_I
CREATION TASKS & VERIFY CONSTRAINTS
197 83
356 51
501 178
21 145
18 54
284 0
277 147
431 0
516 114
514 192
-----------------------------
CHECK F_OBJECTIF
-----------------------------
End time is :  253
True
-----------------------------
END
-----------------------------
-----------------------------
Working on dense_10_30_3_3_I
CREATION TASKS & VERIFY CONSTRAINTS
29 75
138 170
505 170
382 155
17 135
237 173
201 170
447 54
281 0
472 162
-----------------------------
CHECK F_OBJECTIF
-----------------------------
End time is :  254
True
-----------------------------
END
-----------------------------
-----------------------------
Worki