In [1]:
import glob
import os
import numpy as np
import time
import math
from DataProcess import *
from SolutionChecker import *
from LocalSearch import *
import cProfile

In [2]:
l1 = ['dense', 'medium', 'sparse']
common = '_10_30_3_'
filelist = []
for item in l1:
    for i in range(1, 11):
        filelist.append(item + common + str(i)+ '_I')
print(filelist)

['dense_10_30_3_1_I', 'dense_10_30_3_2_I', 'dense_10_30_3_3_I', 'dense_10_30_3_4_I', 'dense_10_30_3_5_I', 'dense_10_30_3_6_I', 'dense_10_30_3_7_I', 'dense_10_30_3_8_I', 'dense_10_30_3_9_I', 'dense_10_30_3_10_I', 'medium_10_30_3_1_I', 'medium_10_30_3_2_I', 'medium_10_30_3_3_I', 'medium_10_30_3_4_I', 'medium_10_30_3_5_I', 'medium_10_30_3_6_I', 'medium_10_30_3_7_I', 'medium_10_30_3_8_I', 'medium_10_30_3_9_I', 'medium_10_30_3_10_I', 'sparse_10_30_3_1_I', 'sparse_10_30_3_2_I', 'sparse_10_30_3_3_I', 'sparse_10_30_3_4_I', 'sparse_10_30_3_5_I', 'sparse_10_30_3_6_I', 'sparse_10_30_3_7_I', 'sparse_10_30_3_8_I', 'sparse_10_30_3_9_I', 'sparse_10_30_3_10_I']


In [3]:
source_path = os.path.dirname(os.path.abspath('__file__')) + '/InstancesInt/'

In [4]:
for item in filelist:
    print('Generating solution for ' + item)
    EVA_TREE,GRAPH,_ = read_data(source_path + item + '.full')
    endtime,solution,algo_name,exc_time = LocalSearchRandomStart2(EVA_TREE,GRAPH,n_iter=10,n_start_points=2)
    create_solution_file3(item,solution,endtime,algo_name,exc_time)

Generating solution for dense_10_30_3_1_I
Add evacuation info
Add graph info
---------------------------Start n.1---------------------------
Iteration 0:
[384, 163, 285, 359, 275, 268, 227, 279, 323, 344]  =>  184
Iteration 1:
[285 163 384 359 275 268 227 279 323 344]  =>  180
Iteration 2:
[285 163 384 359 275 268 227 279 323 344]  =>  180
Iteration 3:
[285 163 384 359 275 268 227 279 323 344]  =>  180
Iteration 4:
[285 163 384 359 275 268 227 279 323 344]  =>  180
Iteration 5:
[285 163 384 359 275 268 227 279 323 344]  =>  180
----------------------------------------------------------------
---------------------------Start n.2---------------------------
Iteration 0:
[163, 384, 227, 323, 268, 285, 359, 275, 279, 344]  =>  184
Iteration 1:
[163 285 227 323 268 384 359 275 279 344]  =>  180
Iteration 2:
[163 285 227 323 268 384 359 275 279 344]  =>  180
Iteration 3:
[163 285 227 323 268 384 359 275 279 344]  =>  180
Iteration 4:
[163 285 227 323 268 384 359 275 279 344]  =>  180
Iteratio

Iteration 0:
[493, 70, 489, 236, 174, 233, 273, 370, 346, 427]  =>  280
Iteration 1:
[346  70 489 236 174 233 273 370 493 427]  =>  275
Iteration 2:
[346 493 489 236 174 233 273 370  70 427]  =>  273
Iteration 3:
[346 493 489 370 174 233 273 236  70 427]  =>  254
Iteration 4:
[346 493 489 370 174 233 273 236  70 427]  =>  254
Iteration 5:
[346 493 489 370 174 233 273 236  70 427]  =>  254
Iteration 6:
[346 493 489 370 174 233 273 236  70 427]  =>  254
Iteration 7:
[346 493 489 370 174 233 273 236  70 427]  =>  254
----------------------------------------------------------------
---------------------------Start n.2---------------------------
Iteration 0:
[489, 174, 273, 493, 346, 236, 370, 427, 233, 70]  =>  261
Iteration 1:
[370 174 273 493 346 236 489 427 233  70]  =>  254
Iteration 2:
[370 174 273 493 346 236 489 427 233  70]  =>  254
Iteration 3:
[370 174 273 493 346 236 489 427 233  70]  =>  254
Iteration 4:
[370 174 273 493 346 236 489 427 233  70]  =>  254
Iteration 5:
[370 174 2

[134, 176, 289, 230, 119, 377, 256, 294, 125, 379]  =>  305
Iteration 1:
[134 125 289 230 119 377 256 294 176 379]  =>  295
Iteration 2:
[134 125 289 230 119 377 256 294 176 379]  =>  295
Iteration 3:
[134 125 289 230 119 377 256 294 176 379]  =>  295
Iteration 4:
[134 125 289 230 119 377 256 294 176 379]  =>  295
Iteration 5:
[134 125 289 230 119 377 256 294 176 379]  =>  295
----------------------------------------------------------------
Add evacuation info
Add graph info
Generating solution for medium_10_30_3_5_I
Add evacuation info
Add graph info
---------------------------Start n.1---------------------------
Iteration 0:
[39, 184, 192, 365, 105, 259, 393, 108, 226, 420]  =>  268
Iteration 1:
[ 39 184 226 365 105 259 393 108 192 420]  =>  259
Iteration 2:
[ 39 184 226 365 105 259 393 108 192 420]  =>  259
Iteration 3:
[ 39 184 226 365 105 259 393 108 192 420]  =>  259
Iteration 4:
[ 39 184 226 365 105 259 393 108 192 420]  =>  259
Iteration 5:
[ 39 184 226 365 105 259 393 108 192 

Iteration 4:
[134 177 128 156 190  77 107 167 138 130]  =>  143
Iteration 5:
[134 177 128 156 190  77 107 167 138 130]  =>  143
----------------------------------------------------------------
---------------------------Start n.2---------------------------
Iteration 0:
[190, 177, 134, 138, 156, 167, 128, 130, 77, 107]  =>  174
Iteration 1:
[ 77 177 134 138 156 167 128 130 190 107]  =>  150
Iteration 2:
[ 77 177 167 138 156 134 128 130 190 107]  =>  145
Iteration 3:
[ 77 177 167 138 156 134 128 190 130 107]  =>  140
Iteration 4:
[ 77 177 167 138 156 134 128 190 130 107]  =>  140
Iteration 5:
[ 77 177 167 138 156 134 128 190 130 107]  =>  140
Iteration 6:
[ 77 177 167 138 156 134 128 190 130 107]  =>  140
Iteration 7:
[ 77 177 167 138 156 134 128 190 130 107]  =>  140
----------------------------------------------------------------
Add evacuation info
Add graph info
Generating solution for sparse_10_30_3_2_I
Add evacuation info
Add graph info
---------------------------Start n.1---------

[186, 106, 91, 79, 30, 191, 72, 247, 236, 98]  =>  234
Iteration 1:
[186 106 236  79  30 191  72 247  91  98]  =>  224
Iteration 2:
[186 106 236  79  30 191  72 247  91  98]  =>  224
Iteration 3:
[186 106 236  79  30 191  72 247  91  98]  =>  224
Iteration 4:
[186 106 236  79  30 191  72 247  91  98]  =>  224
Iteration 5:
[186 106 236  79  30 191  72 247  91  98]  =>  224
----------------------------------------------------------------
---------------------------Start n.2---------------------------
Iteration 0:
[247, 30, 191, 106, 98, 91, 79, 186, 72, 236]  =>  236
Iteration 1:
[ 79  30 191 106  98  91 247 186  72 236]  =>  228
Iteration 2:
[236  30 191 106  98  91 247 186  72  79]  =>  224
Iteration 3:
[236  30 191 106  98  91 247 186  72  79]  =>  224
Iteration 4:
[236  30 191 106  98  91 247 186  72  79]  =>  224
Iteration 5:
[236  30 191 106  98  91 247 186  72  79]  =>  224
Iteration 6:
[236  30 191 106  98  91 247 186  72  79]  =>  224
--------------------------------------------

In [12]:
filename = os.path.dirname(os.path.abspath('__file__')) + '/Borne_Inf_List.csv'
f = open(filename, 'w')
t = 0
f.write('File_name, Nb_evac_nodes, Graph_length, Borne_Inf, Execution_time\n')
for item in filelist:
    print('Generating infimum for ' + item)
    f.write(item + ', ')
    EVA_TREE,GRAPH,NB_NODES = read_data(source_path + item + '.full')
    NB_EVA_NODES = len(EVA_TREE)
    NB_EDGES = len(GRAPH)
    LIST_EVA_NODES = [item[0] for item in EVA_TREE]
    f.write(str(NB_EVA_NODES) + ', ')
    f.write(str(NB_EDGES) + ', ')
    #f.write(str(NB_EVA_NODES * NB_EDGES) + ', ')
    t = time.time()
    res = get_borne_inf(LIST_EVA_NODES,EVA_TREE,GRAPH)
    t = time.time() - t
    f.write(str(res) + ', ')
    f.write(str(t) + '\n')
    
f.close()

Generating infimum for dense_10_30_3_1_I
Add evacuation info
Add graph info
Generating infimum for dense_10_30_3_2_I
Add evacuation info
Add graph info
Generating infimum for dense_10_30_3_3_I
Add evacuation info
Add graph info
Generating infimum for dense_10_30_3_4_I
Add evacuation info
Add graph info
Generating infimum for dense_10_30_3_5_I
Add evacuation info
Add graph info
Generating infimum for dense_10_30_3_6_I
Add evacuation info
Add graph info
Generating infimum for dense_10_30_3_7_I
Add evacuation info
Add graph info
Generating infimum for dense_10_30_3_8_I
Add evacuation info
Add graph info
Generating infimum for dense_10_30_3_9_I
Add evacuation info
Add graph info
Generating infimum for dense_10_30_3_10_I
Add evacuation info
Add graph info
Generating infimum for medium_10_30_3_1_I
Add evacuation info
Add graph info
Generating infimum for medium_10_30_3_2_I
Add evacuation info
Add graph info
Generating infimum for medium_10_30_3_3_I
Add evacuation info
Add graph info
Generati

In [17]:
filename = os.path.dirname(os.path.abspath('__file__')) + '/Borne_Sup_List.csv'
f = open(filename, 'w')
res = 0
avg = 0
t = 0
l = []
f.write('File_name, Nb_evac_nodes, Graph_length, Borne_Sup_Min, Borne_Sup_Max, Avg_Execution_time\n')
for item in filelist:
    print('Generating infimum for ' + item)
    f.write(item + ', ')
    EVA_TREE,GRAPH,NB_NODES = read_data(source_path + item + '.full')
    NB_EVA_NODES = len(EVA_TREE)
    NB_EDGES = len(GRAPH)
    LIST_EVA_NODES = [item[0] for item in EVA_TREE]
    f.write(str(NB_EVA_NODES) + ', ')
    f.write(str(NB_EDGES) + ', ')
    #f.write(str(NB_EVA_NODES * NB_EDGES) + ', ')
    for i in range(1, 11):
        t = time.time()
        res = get_borne_sup(LIST_EVA_NODES,EVA_TREE,GRAPH)[0]
        t = time.time() - t
        l.append(res)
        avg = avg + t/float(10)
    f.write(str(min(l)) + ', ')
    f.write(str(max(l)) + ', ')
    f.write(str(avg) + '\n')
    
f.close()

Generating infimum for dense_10_30_3_1_I
Add evacuation info
Add graph info
Generating infimum for dense_10_30_3_2_I
Add evacuation info
Add graph info
Generating infimum for dense_10_30_3_3_I
Add evacuation info
Add graph info
Generating infimum for dense_10_30_3_4_I
Add evacuation info
Add graph info
Generating infimum for dense_10_30_3_5_I
Add evacuation info
Add graph info
Generating infimum for dense_10_30_3_6_I
Add evacuation info
Add graph info
Generating infimum for dense_10_30_3_7_I
Add evacuation info
Add graph info
Generating infimum for dense_10_30_3_8_I
Add evacuation info
Add graph info
Generating infimum for dense_10_30_3_9_I
Add evacuation info
Add graph info
Generating infimum for dense_10_30_3_10_I
Add evacuation info
Add graph info
Generating infimum for medium_10_30_3_1_I
Add evacuation info
Add graph info
Generating infimum for medium_10_30_3_2_I
Add evacuation info
Add graph info
Generating infimum for medium_10_30_3_3_I
Add evacuation info
Add graph info
Generati