In [1]:
import glob
import os
import numpy as np
import math
from DataProcess import *
from SolutionChecker import *
from LocalSearch import *
import cProfile

In [2]:
data_path = os.path.dirname(os.path.abspath('__file__')) + "/data/wildfire.data"

In [3]:
solution_path = os.path.dirname(os.path.abspath('__file__')) + "/data/wildfire.solution"

In [4]:
print_data(data_path)

Add evacuation info
Add graph info
-----------------------------
evacuation_tree =  [[1, 48, 8, 3, 4, 5, 6], [2, 30, 5, 3, 4, 5, 6], [3, 33, 3, 2, 5, 6]]
graph =  [[1, 4, 9223372036854775807, 7, 8], [2, 4, 9223372036854775807, 4, 5], [3, 5, 9223372036854775807, 6, 3], [4, 5, 9223372036854775807, 9, 10], [5, 6, 9223372036854775807, 12, 11]]
number of evacuation nodes :  3
List of evac nodes :  [1, 2, 3]
number of nodes =  6
number of edges =  5
-----------------------------


0

In [5]:
print_solution(solution_path)

-----------------------------
A solution is : [[1, 8, 3], [2, 5, 0], [3, 3, 0]]
f_objectif =  37
Nature of solution :  valid
-----------------------------


0

In [6]:
verify_solution(data_path,solution_path)

Add evacuation info
Add graph info
Add evacuation info
Add graph info
-----------------------------
evacuation_tree =  [[1, 48, 8, 3, 4, 5, 6], [2, 30, 5, 3, 4, 5, 6], [3, 33, 3, 2, 5, 6]]
graph =  [[1, 4, 9223372036854775807, 7, 8], [2, 4, 9223372036854775807, 4, 5], [3, 5, 9223372036854775807, 6, 3], [4, 5, 9223372036854775807, 9, 10], [5, 6, 9223372036854775807, 12, 11]]
number of evacuation nodes :  3
List of evac nodes :  [1, 2, 3]
number of nodes =  6
number of edges =  5
-----------------------------
-----------------------------
A solution is : [[1, 8, 3], [2, 5, 0], [3, 3, 0]]
f_objectif =  37
Nature of solution :  valid
-----------------------------
CREATION TASKS & VERIFY CONSTRAINTS
-----------------------------
ressources info after evacuation =  {'Cap of edge[1-4]': array([8, 8, 8, 0, 0, 0, 0, 0, 0, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
       8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8]), 'Cap of edge[2-4]': array([0, 0, 0, 0, 0, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5

True

In [7]:
EVA_TREE,GRAPH,NB_NODES = read_data(data_path)
NB_EVA_NODES = len(EVA_TREE)
NB_EDGES = len(GRAPH)
LIST_EVA_NODES = [item[0] for item in EVA_TREE]

Add evacuation info
Add graph info


In [8]:
# for i in range(NB_EVA_NODES) : 
#     node_id = EVA_TREE[i][0]
#     print('Evacuation of (only) node ',node_id,' is ', get_duration(node_id,EVA_TREE,GRAPH),' mins')

In [9]:
print('Borne inferieur = {} mins'.format(get_borne_inf(LIST_EVA_NODES,EVA_TREE,GRAPH)))

Borne inferieur = 34 mins


In [10]:
endtime,init_sol= get_borne_sup(LIST_EVA_NODES,EVA_TREE,GRAPH)
print('Borne superieur = {} mins'.format(endtime))
init_sol

Borne superieur = 37 mins


[[2, 5, 0], [3, 3, 0], [1, 8, 3]]

In [11]:
data_path_2 = os.path.dirname(os.path.abspath('__file__')) + "/data/dense.data"
EVA_TREE,GRAPH,NB_NODES = read_data(data_path_2)
NB_EVA_NODES = len(EVA_TREE)
NB_EDGES = len(GRAPH)
LIST_EVA_NODES = [item[0] for item in EVA_TREE]

Add evacuation info
Add graph info


In [12]:
print_data(data_path_2)

Add evacuation info
Add graph info
-----------------------------
evacuation_tree =  [[227, 2483, 71, 19, 237, 244, 57, 529, 548, 70, 87, 111, 503, 382, 531, 225, 481, 489, 493, 437, 385, 346, 373], [344, 157, 72, 25, 221, 257, 264, 162, 77, 3, 19, 29, 57, 529, 548, 70, 87, 111, 503, 382, 531, 225, 481, 489, 493, 437, 385, 346, 373], [323, 986, 71, 20, 333, 337, 342, 498, 515, 520, 209, 216, 473, 161, 166, 170, 211, 250, 281, 310, 328, 336, 346, 373], [268, 2792, 132, 11, 230, 486, 170, 211, 250, 281, 310, 328, 336, 346, 373], [275, 1707, 70, 23, 113, 372, 78, 83, 337, 342, 498, 515, 520, 209, 216, 473, 161, 166, 170, 211, 250, 281, 310, 328, 336, 346, 373], [279, 2090, 72, 38, 179, 92, 110, 124, 187, 140, 484, 158, 109, 118, 160, 42, 51, 518, 523, 528, 537, 545, 3, 19, 29, 57, 529, 548, 70, 87, 111, 503, 382, 531, 225, 481, 489, 493, 437, 385, 346, 373], [359, 1155, 70, 52, 189, 410, 456, 458, 56, 58, 202, 205, 208, 519, 16, 90, 98, 114, 132, 55, 20, 527, 421, 332, 247, 190, 142, 61, 5

0

In [13]:
print('Borne inferieur = {} mins'.format(get_borne_inf(LIST_EVA_NODES,EVA_TREE,GRAPH)))

Borne inferieur = 91 mins


In [14]:
endtime,init_sol= get_borne_sup(LIST_EVA_NODES,EVA_TREE,GRAPH)
print('Borne superieur = {} mins'.format(endtime))
init_sol

Borne superieur = 184 mins


[[323, 71, 0],
 [384, 71, 0],
 [163, 70, 15],
 [344, 71, 33],
 [268, 132, 70],
 [279, 71, 18],
 [275, 70, 91],
 [227, 71, 77],
 [285, 71, 113],
 [359, 70, 120]]

In [15]:
cp = cProfile.Profile()
cp.enable()
endtime,best_solution= LocalSearchRun(init_sol,EVA_TREE,GRAPH,n_iter=10)
cp.disable()
cp.print_stats()

Iteration 0:
[323, 384, 163, 279, 344, 268, 227, 275, 285, 359]  =>  184
Iteration 1:
[285 384 163 279 344 268 227 275 323 359]  =>  180
Iteration 2:
[285 384 163 279 344 268 227 275 323 359]  =>  180
Iteration 3:
[285 384 163 279 344 268 227 275 323 359]  =>  180
Iteration 4:
[285 384 163 279 344 268 227 275 323 359]  =>  180
Iteration 5:
[285 384 163 279 344 268 227 275 323 359]  =>  180
         4587082 function calls (4587052 primitive calls) in 22.658 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000   22.658   22.658 <ipython-input-15-460573cdb635>:3(<module>)
        1    0.000    0.000    0.000    0.000 <ipython-input-15-460573cdb635>:4(<module>)
     2710    0.039    0.000    3.548    0.001 DataProcess.py:102(get_task)
     2710    0.069    0.000    3.354    0.001 DataProcess.py:106(<listcomp>)
      271    0.016    0.000    1.603    0.006 DataProcess.py:121(create_solution)
     2710    0

In [16]:
# cp = cProfile.Profile()
# cp.enable()
# best_solution,endtime = LocalSearchRun2(init_sol,EVA_TREE,GRAPH,n_iter=10)
# cp.disable()
# cp.print_stats()

In [17]:
print('solution = ',best_solution)
print('end time = ',endtime)

solution =  [[285, 71, 0], [384, 71, 19], [163, 70, 0], [279, 71, 34], [344, 71, 82], [268, 132, 55], [227, 71, 96], [275, 70, 76], [323, 71, 100], [359, 70, 116]]
end time =  180


In [18]:
cp = cProfile.Profile()
cp.enable()
endtime,best_solution = LocalSearchRandomStart(EVA_TREE,GRAPH,n_iter=10,n_start_points=2)
cp.disable()
cp.print_stats()
print('solution = ',best_solution)
print('end time = ',endtime)

---------------------------Start n.1---------------------------
Iteration 0:
[344, 275, 359, 323, 285, 268, 227, 163, 384, 279]  =>  193
Iteration 1:
[285 275 359 323 344 268 227 163 384 279]  =>  180
Iteration 2:
[285 275 359 323 344 268 227 163 384 279]  =>  180
Iteration 3:
[285 275 359 323 344 268 227 163 384 279]  =>  180
Iteration 4:
[285 275 359 323 344 268 227 163 384 279]  =>  180
Iteration 5:
[285 275 359 323 344 268 227 163 384 279]  =>  180
----------------------------------------------------------------
---------------------------Start n.2---------------------------
Iteration 0:
[344, 275, 384, 163, 227, 359, 323, 268, 279, 285]  =>  192
Iteration 1:
[285 275 384 163 227 359 323 268 279 344]  =>  180
Iteration 2:
[285 275 384 163 227 359 323 268 279 344]  =>  180
Iteration 3:
[285 275 384 163 227 359 323 268 279 344]  =>  180
Iteration 4:
[285 275 384 163 227 359 323 268 279 344]  =>  180
Iteration 5:
[285 275 384 163 227 359 323 268 279 344]  =>  180
---------------------

In [19]:
create_solution_file('data/wildfire_sup.solution',best_solution,endtime)

0

In [20]:
# #-----------------------------------------------------------------------------
# # Build the model
# #-----------------------------------------------------------------------------
# from docplex.cp.model import CpoModel
# from docplex.cp.expression import *
# from docplex.cp.solution import *
# import docplex.cp.utils_visu as visu
# # Create model
# mdl = CpoModel(version='12.7.0')

In [21]:
# # Create one interval variable per job operation
# E_nodes = [[mdl.interval_var(size=get_task(j,EVA_TREE,GRAPH)[0], name="Evacuees from {} at {}".format(j,m)) for m in get_task(j,EVA_TREE,GRAPH)[1]] for j in LIST_EVA_NODES]
# len(E_nodes)

In [22]:
# len(E_nodes[0])

In [23]:
# #-----------------------------------------------------------------------------
# # Constraints 
# #-----------------------------------------------------------------------------

# #Each operation must start after a precise duration = time to traverse an arc
# for i in range(NB_EVA_NODES) :
#     root = LIST_EVA_NODES[i]
#     route_list = get_task(root,EVA_TREE,GRAPH)[1]
#     route_len = len(route_list)
#     current = root
#     for m in range(route_len) :
#         nxt = route_list[m]
# #         print("Node-{}-to-{}".format(root,nxt))
#         if nxt != current :
# #             print(current,nxt)
#             _,delay,_ = get_edge_info(current,nxt,GRAPH)
#             mdl.add(mdl.start_at_start(E_nodes[i][m-1],E_nodes[i][m],delay))
#             print("Evacuees-from-{}-at-{} starts after Evacuees-from-{}-at-{} : {} mins ".format(root,nxt,root,current,delay))
#         current = nxt
#     print('----------')

In [24]:
# #Constraint on capacity of ressources, which are edges of graph

# for r in range(NB_EDGES) :
#     edge = GRAPH[r]
# #     print(edge)
#     CAP_MAX = edge[-1]
#     rsc = 0
#     ressources = []
#     for i in range(NB_EVA_NODES) :
#         root = LIST_EVA_NODES[i]
#         _,route_list,capacity = get_task(root,EVA_TREE,GRAPH)
#         route_len = len(route_list)
#         current = root

#         for m in range(route_len) : 
#             nxt = route_list[m]

#             if edge[0] == current and edge[1]==nxt :
#                 ressources.append(mdl.pulse(E_nodes[i][m-1],capacity))
#                 print("Evacuees-from-{}-at-{} requests edge [{}-{}] a capacity {}".format(root,route_list[m-1],current,nxt,capacity))
                
#                 rsc += capacity
               
#             current = nxt
#         #end for
#     #end for
#     mdl.add(mdl.sum(ressources) <= CAP_MAX)
#     print('Constraint on edge {}-{} with capacity_max {}... is loaded'.format(edge[0],edge[1],CAP_MAX))
#     print('--------------')
# #end for

In [25]:
# #Minimize end of all tasks
# mdl.add(mdl.minimize(mdl.max([mdl.end_of(node) for list_nodes in E_nodes for node in list_nodes])))

In [26]:
# #-----------------------------------------------------------------------------
# # Solve the model and display the result
# #-----------------------------------------------------------------------------
# mdl.write_information()

In [27]:
# # Solve model
# # print("Solving model....")
# msol = mdl.solve(TimeLimit=1000)
# # print("Solution: ")
# msol.print_solution()