In [1]:
import glob
import os
import numpy as np
import math
from DataProcess import *
from SolutionChecker import *
from LocalSearch import *

# Test for Input TD

In [2]:
data_path = os.path.dirname(os.path.abspath('__file__')) + "/data/wildfire.data"

In [3]:
solution_path = os.path.dirname(os.path.abspath('__file__')) + "/data/wildfire.solution"

In [4]:
# print_data(data_path)

In [5]:
#print_solution(solution_path)

In [6]:
#verify_solution(data_path,solution_path)

In [7]:
# EVA_TREE,GRAPH,NB_NODES = read_data(data_path)
# NB_EVA_NODES = len(EVA_TREE)
# NB_EDGES = len(GRAPH)
# LIST_EVA_NODES = [item[0] for item in EVA_TREE]

In [8]:
# for i in range(NB_EVA_NODES) : 
#     node_id = EVA_TREE[i][0]
#     print('Evacuation of (only) node ',node_id,' is ', get_duration(node_id,EVA_TREE,GRAPH),' mins')

In [9]:
# print('Borne inferieur = {} mins'.format(get_borne_inf(LIST_EVA_NODES,EVA_TREE,GRAPH)))

In [10]:
# endtime,init_sol= get_borne_sup(LIST_EVA_NODES,EVA_TREE,GRAPH)
# print('Borne superieur = {} mins'.format(endtime))
# init_sol

In [11]:
# cp = cProfile.Profile()
# cp.enable()
# endtime,best_solution= LocalSearchRun2(init_sol,EVA_TREE,GRAPH,n_iter=10)
# cp.disable()
# cp.print_stats()

# Test for given instances 

In [12]:
# data_path_2 = os.path.dirname(os.path.abspath('__file__')) + "/InstancesInt/dense_10_30_3_1_I.full"
# EVA_TREE,GRAPH,NB_NODES = read_data(data_path_2)
# NB_EVA_NODES = len(EVA_TREE)
# NB_EDGES = len(GRAPH)
# LIST_EVA_NODES = [item[0] for item in EVA_TREE]

In [13]:
#print_data(data_path_2)

In [14]:
# print('Borne inferieur = {} mins'.format(get_borne_inf(LIST_EVA_NODES,EVA_TREE,GRAPH)))

In [15]:
# endtime,init_sol= get_borne_sup(LIST_EVA_NODES,EVA_TREE,GRAPH)
# print('Borne superieur = {} mins'.format(endtime))
# init_sol

In [16]:
# cp = cProfile.Profile()
# cp.enable()
# endtime,best_solution= LocalSearchRun(init_sol,EVA_TREE,GRAPH,n_iter=10)
# cp.disable()
# cp.print_stats()

In [17]:
# cp = cProfile.Profile()
# cp.enable()
# endtime,best_solution= LocalSearchRun4(init_sol,EVA_TREE,GRAPH,n_iter=10)
# cp.disable()
# cp.print_stats()

In [18]:
# cp = cProfile.Profile()
# cp.enable()
# best_solution,endtime = LocalSearchRun2(init_sol,EVA_TREE,GRAPH,n_iter=10)
# cp.disable()
# cp.print_stats()

In [19]:
# print('solution = ',best_solution)
# print('end time = ',endtime)

In [20]:
# cp = cProfile.Profile()
# cp.enable()
# endtime,best_solution,algo,exc = LocalSearchRandomStart2(EVA_TREE,GRAPH,n_iter=10,n_start_points=5)
# create_solution_file3('dense_10_30_3_1_I',best_solution,endtime,algo,exc)
# cp.disable()
# cp.print_stats()
# print('solution = ',best_solution)
# print('end time = ',endtime)

In [21]:
# create_solution_file('data/wildfire_sup.solution',best_solution,endtime)

# Test with due_date problem

In [22]:
import glob
import os
import numpy as np
import math
from DataProcess import *
from SolutionChecker import *
from LocalSearch import *

In [43]:
data_path = os.path.dirname(os.path.abspath('__file__')) + "/InstancesInt/dense_10_30_3_1_I.full"
EVA_TREE,GRAPH,NB_NODES = read_data(data_path)
NB_EVA_NODES = len(EVA_TREE)
NB_EDGES = len(GRAPH)
LIST_EVA_NODES = [item[0] for item in EVA_TREE]

#Run a local search to find a solution
endtime,best_solution,algo,exc = LocalSearchRandomStart2(EVA_TREE,GRAPH,n_iter=10,n_start_points=1)
create_solution_file3('dense_10_30_3_1_I',best_solution,endtime,algo,exc)

print('solution = ',best_solution)
print('end time = ',endtime)

# # verify this solution by our checker
# solution_path = os.path.dirname(os.path.abspath('__file__')) + "/Solutions/dense_10_30_3_1_I.solution"
# verify_solution(data_path,solution_path)

check_a_solution(data_path,best_solution)
s = create_ordered_list_of(best_solution)
get_end_time_3(s,EVA_TREE,GRAPH)

---------------------------Start n.1---------------------------
Iteration 0:
[344, 275, 285, 359, 279, 268, 323, 163, 384, 227]  =>  192
Iteration 1:
[285 275 344 359 279 268 323 163 384 227]  =>  180
Iteration 2:
[285 275 344 359 279 268 323 163 384 227]  =>  180
Iteration 3:
[285 275 344 359 279 268 323 163 384 227]  =>  180
Iteration 4:
[285 275 344 359 279 268 323 163 384 227]  =>  180
Iteration 5:
[285 275 344 359 279 268 323 163 384 227]  =>  180
----------------------------------------------------------------
solution =  [[285, 71, 0], [275, 70, 0], [344, 71, 11], [359, 70, 10], [279, 71, 13], [268, 132, 26], [323, 71, 46], [163, 70, 61], [384, 71, 69], [227, 71, 113]]
end time =  180
CREATION TASKS & VERIFY CONSTRAINTS
ERROR ON DUE DATE [57-244]


(99999,
 [[285, 123, 0],
  [275, 192, 0],
  [359, 174, 7],
  [344, 186, 28],
  [279, 192, 13],
  [268, 192, 26],
  [323, 192, 46],
  [163, 192, 61],
  [384, 174, 69],
  [227, 180, 113]])

In [41]:
data_path = os.path.dirname(os.path.abspath('__file__')) + "/InstancesInt/dense_10_30_3_1_I.full"
EVA_TREE,GRAPH,NB_NODES = read_data(data_path)
NB_EVA_NODES = len(EVA_TREE)
NB_EDGES = len(GRAPH)
LIST_EVA_NODES = [item[0] for item in EVA_TREE]

#Run a local search to find a solution
endtime,best_solution,algo,exc = LocalSearchRandomStart3(EVA_TREE,GRAPH,n_iter=10,n_start_points=2)
create_solution_file3('dense_10_30_3_1_I',best_solution,endtime,algo,exc)

print('solution = ',best_solution)
print('end time = ',endtime)

# verify this solution by our checker
solution_path = os.path.dirname(os.path.abspath('__file__')) + "/Solutions/dense_10_30_3_1_I.solution"
verify_solution(data_path,solution_path)

---------------------------Start n.1---------------------------
Iteration 0:
[227, 163, 359, 344, 279, 275, 323, 384, 268, 285]  =>  99999
Iteration 1:
[227 163 285 344 279 275 323 384 268 359]  =>  181
Iteration 2:
[285 163 227 344 279 275 323 384 268 359]  =>  180
Iteration 3:
[285 163 227 344 279 275 323 384 268 359]  =>  180
Iteration 4:
[285 163 227 344 279 275 323 384 268 359]  =>  180
Iteration 5:
[285 163 227 344 279 275 323 384 268 359]  =>  180
Iteration 6:
[285 163 227 344 279 275 323 384 268 359]  =>  180
----------------------------------------------------------------
---------------------------Start n.2---------------------------
Iteration 0:
[384, 275, 279, 323, 268, 163, 285, 359, 344, 227]  =>  99999
Iteration 1:
[227 275 279 323 268 163 285 359 344 384]  =>  181
Iteration 2:
[227 275 279 323 268 163 285 359 344 384]  =>  181
Iteration 3:
[227 275 279 323 268 163 285 359 344 384]  =>  181
Iteration 4:
[227 275 279 323 268 163 285 359 344 384]  =>  181
Iteration 5:
[227

True